### PR TITLE
Drop old stuff

### PR DESCRIPTION
**Pull request by kammala**
- dropping old versions of python (2.7, anything prior to 3.8) and related code (metadata in `__ini__.py`, py2-related dependencies, etc)
- replacing travis with github actions
- introduce autoformatters
- introduce optional (manual) semi-automatic release process via `python-semantic-version`

### CODE REVIEW

**Comment by pennersr** [comment]
Sorry for being picky, but I prefer not to go the poetry route and stick to de facto standards. GitHub actions are nice, though would like to avoid vendor lock-in by keeping tox around and have GitHub actions kick off tox.

**Comment by kammala** [comment]
oops, it was not actually using `poetry` anywhere in CI scripts, it was just some leftover from previous implementation in config files.

don't personally think we are vendor locking ourselves by not using `tox` (e.g. in gitlab / bitbucket we would use the same approach with running separate step in another docker image based on different python version), but for the simplicity of local testing against multiple pythons I've returned it back.

would you mind to take a look again? ^_^

**Comment by pennersr** [comment]
Could it be that you did not push? I don't see any updates?

**Comment by kammala** [comment]
well, first of all, closed PRs do not get updates, so you wouldn't see anything here.
and later on during rebase I've noticed that you have already introduced most of the changes yourself, so my PR would make no sense, so I throw it away :)

**Pull request closed without merging**
